apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - backend/
  - frontend/
  - database/
  - redis/

commonLabels:
  app: alerto26
  managed-by: kustomize
